import type { Rules } from './types'

export const DEFAULT_RULES: Rules = {
  version: 1,
  notes:
    'Edit and save. CreateMeter reloads within a few seconds. Categories: creating | consuming | neutral. App match is name or bundle id (case-insensitive). Host match is hostname or suffix (youtube.com also matches www.youtube.com). Optional pathPrefix limits a host rule to a path, e.g. /document.',
  pollIntervalMs: 1500,
  idleThresholdSeconds: 150,
  browsers: [
    'Safari',
    'com.apple.Safari',
    'Google Chrome',
    'Chrome',
    'com.google.Chrome',
    'Chromium',
    'org.chromium.Chromium',
    'Arc',
    'company.thebrowser.Browser',
    'Brave Browser',
    'Brave',
    'com.brave.Browser',
    'Microsoft Edge',
    'com.microsoft.edgemac',
    'Firefox',
    'org.mozilla.firefox',
    'Orion',
    'com.kagi.kagimacOS',
    'Vivaldi',
    'com.vivaldi.Vivaldi',
    'Opera',
    'com.operasoftware.Opera',
    'Zen Browser',
    'app.zen-browser.zen',
    'Dia',
    'Comet',
    'SigmaOS'
  ],
  apps: [
    { match: 'Cursor', category: 'creating' },
    { match: 'com.todesktop.230313mzl4w4u92', category: 'creating' },
    { match: 'Visual Studio Code', category: 'creating' },
    { match: 'Code - Insiders', category: 'creating' },
    { match: 'com.microsoft.VSCode', category: 'creating' },
    { match: 'Windsurf', category: 'creating' },
    { match: 'Zed', category: 'creating' },
    { match: 'dev.zed.Zed', category: 'creating' },
    { match: 'Xcode', category: 'creating' },
    { match: 'com.apple.dt.Xcode', category: 'creating' },
    { match: 'Terminal', category: 'creating' },
    { match: 'com.apple.Terminal', category: 'creating' },
    { match: 'iTerm', category: 'creating' },
    { match: 'com.googlecode.iterm2', category: 'creating' },
    { match: 'Warp', category: 'creating' },
    { match: 'dev.warp.Warp-Stable', category: 'creating' },
    { match: 'Notion', category: 'creating' },
    { match: 'notion.id', category: 'creating' },
    { match: 'Figma', category: 'creating' },
    { match: 'com.figma.Desktop', category: 'creating' },
    { match: 'Sketch', category: 'creating' },
    { match: 'Final Cut', category: 'creating' },
    { match: 'com.apple.FinalCut', category: 'creating' },
    { match: 'Logic Pro', category: 'creating' },
    { match: 'com.apple.logic10', category: 'creating' },
    { match: 'GarageBand', category: 'creating' },
    { match: 'Pages', category: 'creating' },
    { match: 'com.apple.iWork.Pages', category: 'creating' },
    { match: 'Keynote', category: 'creating' },
    { match: 'com.apple.iWork.Keynote', category: 'creating' },
    { match: 'Numbers', category: 'creating' },
    { match: 'TextEdit', category: 'creating' },
    { match: 'Obsidian', category: 'creating' },
    { match: 'md.obsidian', category: 'creating' },
    { match: 'Bear', category: 'creating' },
    { match: 'net.shinyfrog.bear', category: 'creating' },
    { match: 'Ulysses', category: 'creating' },
    { match: 'Microsoft Word', category: 'creating' },
    { match: 'com.microsoft.Word', category: 'creating' },
    { match: 'Notes', category: 'creating' },
    { match: 'com.apple.Notes', category: 'creating' },
    { match: 'Sublime Text', category: 'creating' },
    { match: 'IntelliJ', category: 'creating' },
    { match: 'WebStorm', category: 'creating' },
    { match: 'PyCharm', category: 'creating' },
    { match: 'Nova', category: 'creating' },
    { match: 'BBEdit', category: 'creating' },
    { match: 'Typora', category: 'creating' },
    { match: 'iA Writer', category: 'creating' },
    { match: 'Drafts', category: 'creating' },
    { match: 'Scrivener', category: 'creating' },
    { match: 'Craft', category: 'creating' },
    { match: 'Logseq', category: 'creating' },
    { match: 'Linear', category: 'creating' },
    { match: 'Miro', category: 'creating' },
    { match: 'Freeform', category: 'creating' },
    { match: 'Pixelmator', category: 'creating' },
    { match: 'Affinity', category: 'creating' },
    { match: 'Photoshop', category: 'creating' },
    { match: 'Illustrator', category: 'creating' },
    { match: 'Premiere', category: 'creating' },
    { match: 'InDesign', category: 'creating' },
    { match: 'Lightroom', category: 'creating' },
    { match: 'DaVinci Resolve', category: 'creating' },
    { match: 'Blender', category: 'creating' },
    { match: 'Descript', category: 'creating' },
    { match: 'ScreenFlow', category: 'creating' },

    { match: 'Safari', category: 'consuming' },
    { match: 'Google Chrome', category: 'consuming' },
    { match: 'Chrome', category: 'consuming' },
    { match: 'Arc', category: 'consuming' },
    { match: 'Brave Browser', category: 'consuming' },
    { match: 'Microsoft Edge', category: 'consuming' },
    { match: 'Firefox', category: 'consuming' },
    { match: 'Orion', category: 'consuming' },
    { match: 'TV', category: 'consuming' },
    { match: 'com.apple.TV', category: 'consuming' },
    { match: 'Podcasts', category: 'consuming' },
    { match: 'News', category: 'consuming' },
    { match: 'com.apple.news', category: 'consuming' },
    { match: 'Music', category: 'consuming' },

    { match: 'Finder', category: 'neutral' },
    { match: 'System Settings', category: 'neutral' },
    { match: 'System Preferences', category: 'neutral' },
    { match: 'Preview', category: 'neutral' },
    { match: 'Calculator', category: 'neutral' },
    { match: 'Calendar', category: 'neutral' },
    { match: 'Mail', category: 'neutral' },
    { match: 'com.apple.mail', category: 'neutral' },
    { match: 'Slack', category: 'neutral' },
    { match: 'Discord', category: 'neutral' },
    { match: 'Messages', category: 'neutral' },
    { match: 'com.apple.MobileSMS', category: 'neutral' },
    { match: 'Telegram', category: 'neutral' },
    { match: 'WhatsApp', category: 'neutral' },
    { match: 'FaceTime', category: 'neutral' },
    { match: 'Zoom', category: 'neutral' },
    { match: 'us.zoom.xos', category: 'neutral' },
    { match: 'Activity Monitor', category: 'neutral' },
    { match: 'Raycast', category: 'neutral' },
    { match: 'Alfred', category: 'neutral' },
    { match: '1Password', category: 'neutral' },
    { match: 'CleanShot', category: 'neutral' },
    { match: 'App Store', category: 'neutral' },
    { match: 'CreateMeter', category: 'neutral' },
    { match: 'Electron', category: 'neutral' }
  ],
  hosts: [
    { host: 'docs.google.com', category: 'creating' },
    { host: 'sheets.google.com', category: 'creating' },
    { host: 'slides.google.com', category: 'creating' },
    { host: 'notion.so', category: 'creating' },
    { host: 'figma.com', category: 'creating' },
    { host: 'figjam.com', category: 'creating' },
    { host: 'canva.com', category: 'creating' },
    { host: 'github.com', category: 'creating' },
    { host: 'gitlab.com', category: 'creating' },
    { host: 'bitbucket.org', category: 'creating' },
    { host: 'localhost', category: 'creating' },
    { host: '127.0.0.1', category: 'creating' },
    { host: 'vercel.app', category: 'creating' },
    { host: 'linear.app', category: 'creating' },
    { host: 'stackblitz.com', category: 'creating' },
    { host: 'codesandbox.io', category: 'creating' },
    { host: 'codepen.io', category: 'creating' },
    { host: 'replit.com', category: 'creating' },
    { host: 'overleaf.com', category: 'creating' },
    { host: 'paper.dropbox.com', category: 'creating' },
    { host: 'coda.io', category: 'creating' },
    { host: 'craft.do', category: 'creating' },
    { host: 'obsidian.md', category: 'creating' },
    { host: 'claude.ai', category: 'creating' },
    { host: 'chatgpt.com', category: 'creating' },
    { host: 'chat.openai.com', category: 'creating' },
    { host: 'cursor.com', category: 'creating' },

    { host: 'youtube.com', category: 'consuming' },
    { host: 'youtu.be', category: 'consuming' },
    { host: 'netflix.com', category: 'consuming' },
    { host: 'twitter.com', category: 'consuming' },
    { host: 'x.com', category: 'consuming' },
    { host: 'instagram.com', category: 'consuming' },
    { host: 'reddit.com', category: 'consuming' },
    { host: 'tiktok.com', category: 'consuming' },
    { host: 'news.ycombinator.com', category: 'consuming' },
    { host: 'nytimes.com', category: 'consuming' },
    { host: 'washingtonpost.com', category: 'consuming' },
    { host: 'wsj.com', category: 'consuming' },
    { host: 'ft.com', category: 'consuming' },
    { host: 'bloomberg.com', category: 'consuming' },
    { host: 'cnn.com', category: 'consuming' },
    { host: 'bbc.com', category: 'consuming' },
    { host: 'bbc.co.uk', category: 'consuming' },
    { host: 'theverge.com', category: 'consuming' },
    { host: 'techcrunch.com', category: 'consuming' },
    { host: 'arstechnica.com', category: 'consuming' },
    { host: 'wired.com', category: 'consuming' },
    { host: 'facebook.com', category: 'consuming' },
    { host: 'twitch.tv', category: 'consuming' },
    { host: 'linkedin.com', category: 'consuming' },
    { host: 'medium.com', category: 'consuming' },
    { host: 'substack.com', category: 'consuming' },
    { host: 'news.google.com', category: 'consuming' },
    { host: 'pinterest.com', category: 'consuming' },
    { host: 'threads.net', category: 'consuming' },
    { host: 'bsky.app', category: 'consuming' },
    { host: 'hulu.com', category: 'consuming' },
    { host: 'disneyplus.com', category: 'consuming' },
    { host: 'max.com', category: 'consuming' },
    { host: 'primevideo.com', category: 'consuming' },
    { host: 'spotify.com', category: 'consuming' },

    { host: 'meet.google.com', category: 'neutral' },
    { host: 'zoom.us', category: 'neutral' },
    { host: 'calendar.google.com', category: 'neutral' },
    { host: 'mail.google.com', category: 'neutral' }
  ],
  defaults: {
    unknownApp: 'neutral',
    unknownBrowserHost: 'consuming'
  }
}
